name = "Orekit"
uuid = "18617f63-0264-4c66-83ad-600754703f99"
authors = ["Helge Eichhorn <git@helgeeichhorn.de>"]
version = "0.1.0"

[deps]
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
JavaCall = "0.7"
julia = "1.5"
